cdp1,ndp1,vu1= input().split()
cdp2,ndp2,vu2= input().split()
valor1=int(cdp1)
valor2=int(ndp1)
valor3=float(vu1)
valor4=int(cdp2)
valor5=int(ndp2)
valor6=float(vu2)
total = (valor2 * valor3 + valor5 * valor6)
total_srt = "{:.2f}".format(total)
print ("VALOR A PAGAR: R$",total_srt)
